### PR TITLE
load external resources with the same protocol as the page itself.

### PR DESCRIPTION
**Pull request by hellerbarde**
Currently, the javascript on the website is not working because jquery is loaded over http:// while the page itself is loaded over https://. That doesn't work on modern browsers anymore.

### CODE REVIEW

**Comment by ginge** [comment]
Thanks!
I see you removed the http entirely. Is that fully supported?

**Comment by hellerbarde** [comment]
As far as i know, thats the canonical way to tell the browser to use the same protocol as the document it is in. But you bring up an interesting question. 
No i am not sure how widely supported it is. I just assumed... 


On July 17, 2017 10:26:06 PM GMT+02:00, Barry Carter <notifications@github.com> wrote:
>Thanks!
>I see you removed the http entirely. Is that fully supported?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ginge/marlin-builder/pull/5#issuecomment-315872470

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hellerbarde** [comment]
actually, it seems that the consensus is to switch from protocol relative URLs to https-always. So maybe you want to amend the pull request before merging, or deny it and make the change yourself :)

Reference: https://stackoverflow.com/questions/28446314/why-use-protocol-relative-urls-at-all

**Comment by ginge** [comment]
interesting. I'm learning a lot here. From reading a couple more pages, you're right I should change to https. Appreciate it either way, thanks!

**Pull request merged**
